############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

imports:
  - path: github.com/zenon4689/hugo-blox-builder/modules/blox-plugin-decap-cms
  - path: github.com/zenon4689/hugo-blox-builder/modules/blox-plugin-netlify
  - path: github.com/zenon4689/hugo-blox-builder/modules/blox-bootstrap/v5
